### ISSUE TITLE
xet cp needs a progress bar

### ISSUE THREAD

**Issue by znation** [xetdata/pyxet#54] opened 2023-08-08 21:18 UTC
There is no progress indicated on `xet cp` commands. These can take quite a while so it appears to have hung. A progress bar would be great!

Related to #53 since the majority of the time spent there might be in the actual upload/download, but it's not clear when the synchronization is done and the upload/download has started.

**Comment by seanses** [comment] 2023-08-10 18:05
Duplicate of https://github.com/xetdata/xethub/issues/3737

**Comment by znation** [comment] 2023-08-10 20:03
@seanses Since this issue is public and that one is private, let's dupe that one against this one.

**Comment by Kelton8Z** [comment] 2023-09-16 15:09
also the xet cp help text needs to indicate that cp only works for remote to remote

**Comment by seanses** [comment] 2023-09-18 17:43
> also the xet cp help text needs to indicate that cp only works for remote to remote

That is not true. It works for (local | remote) <-> (local | remote)

**Comment by Kelton8Z** [comment] 2023-09-29 06:05
> > also the xet cp help text needs to indicate that cp only works for remote to remote
> 
> 
> 
> That is not true. It works for (local | remote) <-> (local | remote)

You are right, could also be made clear in the help text. I only realized what "works everywhere" in Readme meant in hindsight 😅

**Comment by hoytak** [comment] 2023-10-11 21:40
Progress bar in!

**Closed by hoytak** 2023-10-11 21:40 UTC
Labels: bug, enhancement
